googleinterns/trace

src/main/webapp/index-script.js
src/main/webapp/index.html

- Added a method for looking up Places using text. Currently hard-coded to search for the Googleplex building.

Places query

---

src/main/webapp/index-script.js
src/main/webapp/index.html

Searches for nearby locations based on map click.

Search by map

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

Search bar

---

src/main/webapp/index-script.js
src/main/webapp/index.html

- Click black box search icon & map will zoom in on the closest place to your typed input

Search bar registers text input

---

src/main/java/com/google/sps/servlets/LoginServlet.java
src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

- Login button appears above Search bar with working Users API 
- Works great for now BUT am going to try to get the button text to change from Login to Logout depending on status (This will be in a later PR most likely)

Created our initial authentication login

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

Adds tutorial pop-up to front-page along with stubs to scroll left and right, as well as close the pop-up

Incorporate pop up

---

src/main/java/com/google/sps/servlets/LoginServlet.java
src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

The login button now can tell if a user is logged in, and the inner text of the button is adjusted accordingly.

Authentication Modification

---

src/main/webapp/index-script.js

Adding hyperlink implementation in **tidbits** portion of results population in the results modal.

Fix: [Modal Results] Website Hyperlink

---

src/main/webapp/index-script.js

Create filter that checks to remove any undefined tidbit value.

Fix: [Modal Results] undefined tidbit

---

src/main/webapp/index-script.js
src/main/webapp/index.html

Search no longer refreshes the page when pressing enter.

Fix search submit

---

src/main/javaServlets/ReviewServlet.java

- Created a preliminary review servlet that records new reviews in a datastore & returns those reviews when needed.
- This is a skeleton version as we have not discussed entirely what we want to keep in Datastore (especially now with new restrictions)

Created a preliminary Reviews Servlet to keep track of reviews

---

src/main/webapp/index-script.js

Search by text now allows more than 1 result to be printed. 
Modal now allows up to 9 results printed at a time.

Text search

---

src/main/webapp/api.js
src/main/webapp/config.js
src/main/webapp/index.html

**STEPS TO HIDE THE API KEY**
1) Approve and pull this PR to Cloudshell
2) Once we have pulled this so that we each have it, we can remove from github. (Not crucial as we will be deleting the old API key in the next step).
3) Create a new API key and we will individually each delete the one in this file.
4) We each will individually replace the old one in this file with the new one in our personal cloudshells. 
5) Add this file to .gitignore so we don't accidentally commit the new API key to github.

Created a new script js file for the API key

---

src/main/webapp/index-style.css

Changed many pixel values to percents so that tutorial appears on both laptops and monitors.

Tutorial fits all

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/tutorial-pop-up.css

Tutorial now only pops up when users are not logged in.

Tutorial Fix

---

src/main/webapp/index-script.js
src/main/webapp/modal-overlay.css

Functions that toggle between display of review modal body and result modal body.

Feature: [Review Modal] Display Toggle

---

.gitignore
pom.xml
src/main/java/com/google/sps/servlets/PlacesServlet.java
src/main/webapp/config.js

<h1>Creates PlacesServlet.Java</h1>
<p> Currently, this servlet has a doPost function that creates a new instance of a location in our datastore so that we can keep track of a location's average rating. My hope is that the doPost method will be called the first time a user selects the location from SearchResults. </p>
<p>Furthermore, the doGet() method now has the same functionality as what was previously in the ReviewServlet's doGet() method, but tailored to the location; doGet() queries the datastore with all review containing a matching place_id and adds then to a JSONArray to be returned for populating the modal. I expect doGet() will be called each time a location is selected from SearchResults. If the location does not already exist in the datastore, doGet() should call doPost(). …

Places servlet

---

src/main/webapp/index-script.js
src/main/webapp/modal-overlay.css

Fix: [Review Modal] Whitespace

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

- Created a bar next to the search bar where users can add a location to their search. 
- If no location specified, automatically zooms in to where they are located through Places API magic.

Location Search

---

src/main/java/com/google/sps/servlets/VotingServlet.java

Dev had a build failure after pulling PR #66 as int negative was defined twice!

Had variable twice causing build failure

---

src/main/webapp/index-script.js

Merge conflicts resulted in these lines being removed/reverted. Quick Fix.

Oops, code lost in Modal Cohesion

---

src/main/java/com/google/sps/servlets/VotingServlet.java
src/main/webapp/index-style.css

Modified the 'Located by..' button to appear under the search bar (smaller but in the same style as the search bar)

Location fix

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/data/RatingHistory.java
src/main/java/com/google/sps/servlets/ReviewServlet.java

Big emphasis on method decomposition, deliberate choices of variable types, and runtime error squashing.

Fix: [Combine Servlets] Post Method structure

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/ReviewServlet.java

This ended up being quite the heavy task.
- Added Comparators for ```Comment.java```
- Added sorting within ```PlaceReviews.java```
- Added private classifier for methods in both files
` Changed implementation in core servlet to reflect these shifts.

Fix: [Combine Servlets] Duplicate Comments

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html
src/main/webapp/modal-overlay.css
src/main/webapp/newReview.css
src/main/webapp/newReview.html

<ul>
<li>Adds button to add a new review on results page.</li>
<li>Displays new review form on modal while hiding everything else.</li>
<li>Enables user to go from new review form to results page, but not to reviews page. Users can exit from any of the three pages and continue their search normally.</li>
</ul>

New review button

---

src/main/java/com/google/sps/servlets/ReviewServlet.java

Taking inspiration from doPost null checking.
```
if (queryResults.size() == 0) { // There has not been a review before
curLocation = new PlaceReviews(place_id, newReview, rating);
} else { // Add review
curLocation = trimQuery(queryResults);
curLocation.addReview(newReview); // Handles duplicate
}
```

Fix: [Review Servlet] doGet() null check

---

src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/ReviewServlet.java

Important changes to Datastore Entities:
- Datastore Entities are comprised of a ```PlaceReviews``` object.
- **Datastore entity internal IDs are the corresponding MapsAPI Location IDs**

Fix: [Review Servlet] Datastore Put

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/PlacesServlet.java
src/main/java/com/google/sps/servlets/ReviewServlet.java

Database holds reviews and places separately; reviews contain place_id for querying.

Adjust data

---

src/main/webapp/index-script.js
src/main/webapp/index-style.css
src/main/webapp/index.html

- Made the login button appear in the top right corner rather than under the search bar. 
- Geolocation allows the map to center at your location (provided you say yes to location services) 
- Removed duplicate code (login was being styled twice)

08/11/20 Style Changes 

---

src/main/webapp/index-script.js
src/main/webapp/index.html
src/main/webapp/modal-overlay.css

Create buttons for Sorting Reviews.
Buttons for:
- Sort by recency
- Sort by relevancy
Add CSS styling for buttons and their button group
Will be wired with JS sorting scripts hand off from JavaServlet

Feature: [Review Sort] Buttons

---

src/main/webapp/index-script.js
src/main/webapp/index.html
src/main/webapp/modal-overlay.css

Implementation of active styling for review buttons.

Feature: [Review Sort] Buttons Active Styling

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/java/com/google/sps/servlets/VotingServlet.java
src/main/webapp/index-script.js

- Added voters set in comment.java to keep track of who has voted on what comment
- Stores review + voter in a database to keep long-term track of who has voted on what! 
- PlaceReviews keeps track of who is currently logged in so that javascript can access that data during voting.

Users can only vote once on a review. 

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/webapp/index-script.js
src/main/webapp/index.html

This uses the previously created buttons in the Reviews modal to communicate with the backend.
_Button -> Sort Function -> ReFetch with Sort -> Query and Organize -> Present on front end._
This takes advantage of using multiple parameters in the HTTPServletRequest. The `List<Comment>` is sorted within `PlaceReviews` for front-end presentation. This passes basic testing, but not robust.
Changes:
- `Comment.java` Created comparator for ordering by metascore.
- `PlaceReviews.java` Introduce public sorting method `sortReviews(String sortType)`.
- `ReviewServlet.java` Add sortType field to HTTPServletRequest and utilize it.
- `index-script.js` Create comment sorting functions that are wired to appropriate buttons.
- `index.html` Start button group off as hidden.
- `modal-overlay.css` More …

Feature: [Review Sort] JS/Servlet/HTML Cohesion

---

src/main/java/com/google/sps/data/PlaceReviews.java

_Originally posted by @mwo-2020 in https://github.com/googleinterns/trace/pull/96/files/95f102690f27d069beaca6422f61a53f6ea8ed65_

Fix: [Style] Remove sorting before linear search.

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/webapp/index-script.js

>
>
> Ability to Sort Comments by Recency or Rating
> This uses the previously created buttons in the Reviews modal to communicate with the backend.
> _Button -> Sort Function -> ReFetch with Sort -> Query and Organize -> Present on front end._
> This takes advantage of using multiple parameters in the HTTPServletRequest. The `List<Comment>` is sorted within `PlaceReviews` for front-end presentation. This passes basic testing, but not robust.
>
>
> Changes:
>
>- `Comment.java` Created comparator for ordering by metascore.
>- `PlaceReviews.java` Introduce public sorting method `sortReviews(String sortType)`.
>- `ReviewServlet.java` Add sortType field to HTTPServletRequest and utilize it.
>- `index-script.js` Create comment sorting functions that are wired to appropriate buttons.
>- …

Feature: [Review Sort] Full MVP

---

src/main/java/com/google/sps/data/PlaceReviews.java

Indentation issues were due to linter oddity with ```/** */``` function headers.
_Originally referenced by @fyordan in https://github.com/googleinterns/trace/pull/96/files/95f102690f27d069beaca6422f61a53f6ea8ed65_

Fix: [Style] Indentation in PlaceReviews

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/java/com/google/sps/servlets/VotingServlet.java
src/main/webapp/index-script.js

- Votes can be toggled between thumbs up / thumbs down. Can also be removed completely. 
- Datastore containing review-vote pairs also contains if they voted positive or negative, and adjusts accordingly. 
- Each comment has a set of positive voters and negative voters so that javascript can be toggled appropriately. 
- Fixed indentation / camelcase errors. 
Todo; Add style borders / toggle feature so that it is clear which button has been clicked / unclicked.

Switch Vote Capabilities

---

src/main/java/com/google/sps/data/Comment.java
src/main/java/com/google/sps/data/PlaceReviews.java
src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/webapp/index-script.js

- Votes are saved in database, voters saved in positive/negative sets.
- Can remove vote, and change vote from positive to negative.
- Another PR will contain the indication of what has been voted (or not) 
- Another PR will fix the security by not returning the entire list of voters; instead just if they have voted positive/negative individually.

Vote on reviews -> master 

---

src/main/webapp/index-script.js

- If a user has voted, the button which they have voted on will indicate that it has been clicked by having red text. 
- If a user has not voted or changes/removes their vote, the button will contain black text. 
If you have any better indicator ideas, please let me know.

Vote Indicator 

---

src/main/java/com/google/sps/servlets/ReviewServlet.java

I realized there is no need to call 'AddVote' if a user is null, so I added this IF statement to limit our datastore calls.

Limit Datastore Calls

---

src/main/java/com/google/sps/python/heatMap.py
src/main/webapp/index-script.js
src/main/webapp/index.html

-Add markers to map on search
-Animate markers
-Enable user to click on marker to pull up reviews.
-Handle modal display using this pipeline.

Add markers

---

pom.xml

API.JS also had a modification required to allow this to deploy
- At the end of the API link string after libraries=places, add **,visualization**  for it to work.

Change the project ID

---

src/main/webapp/index-script.js
src/main/webapp/index.html

Just adjustin some button tags, you know me

Adjust button styles to better describe their function.

---

src/main/java/com/google/sps/servlets/ReviewServlet.java
src/main/webapp/index-script.js
src/main/webapp/index.html

-Enables user to add url parameter "&testing=true" to pull up fake reviews on any location that is clicked (not sure if the reviews I inserted will persist in other people's datastores, but the idea is basically that, in testing mode, you can add as many reviews as you want and they'll all be aggregated under a generic place_id called testReviews and pulled up no matter where you click).
-Updates reviews page without reloading site

Fake reviews

---

src/main/webapp/index-script.js
src/main/webapp/index.html

- Adds (ugly) sorting buttons to the search result modal (will need to be styled/fit into new UI @dterr)
- Once clicked, search results are sorted, the modal closes & reopens with the brand new sorted search results. 
I do need to do further work on making sure items are being sorted correctly. I wanted to send this out now though because I got to a point where no errors were being thrown & I wanted to give Dominic the buttons to be styled!

Sorting Search Results

---

src/main/webapp/index-script.js

- Modified sorting code to be more efficient BY: 
- Ratings are fetched prior to any clicking (this way it's only once rather than at each click); this allows search results page to contain the rating of each place (which was a requested feature!) and sorting of the ratings happens nearly instantaneous. 
- Removed promises and geolocation on sortbydistance so that can work rapidly.

Sorting - actually works and not slowly!

---

src/main/webapp/index-script.js
src/main/webapp/index.html
src/main/webapp/sidebar.css

PR for addressing comments left in conversation.

Style: Addressing Comments
